use anyhow::{Context, Result};
use chrono::Utc;

use crate::model::{
    CleanupPlan, CleanupPlanAsset, CleanupPlanDocument, Diagnostic, LlmReview, MediaCleanSession,
    QuarantineAction, QuarantineDryRunResult, CLEANUP_PLAN_SCHEMA_VERSION,
    QUARANTINE_RESULT_SCHEMA_VERSION,
};

pub fn analyze_scan_request(
    request: mc_core::CoreScanRequest,
    adapter_diagnostics: Vec<Diagnostic>,
) -> Result<MediaCleanSession> {
    let core_session = mc_core::analyze_request(request).context("mc_core analyze_request")?;
    let mut session: MediaCleanSession =
        serde_json::from_value(serde_json::to_value(core_session)?)
            .context("normalize core session")?;
    session.diagnostics.extend(adapter_diagnostics);
    let (reviews, plans, actions) = build_review_artifacts(&session);
    session.llm_reviews = reviews;
    session.cleanup_plans = plans;
    session.quarantine_actions = actions;
    Ok(session)
}

pub fn build_cleanup_plan(session: &MediaCleanSession) -> CleanupPlanDocument {
    CleanupPlanDocument {
        schema_version: CLEANUP_PLAN_SCHEMA_VERSION.to_string(),
        source_session_id: session.session_id.clone(),
        generated_at: Utc::now().to_rfc3339_opts(chrono::SecondsFormat::Millis, true),
        plans: session.cleanup_plans.clone(),
        assets: session
            .assets
            .iter()
            .map(|asset| CleanupPlanAsset {
                id: asset.id.clone(),
                uri: asset.uri.clone(),
                media_type: asset.media_type.clone(),
                file_size: asset.file_size,
            })
            .collect(),
    }
}

pub fn build_quarantine_dry_run(plan: &CleanupPlanDocument) -> QuarantineDryRunResult {
    QuarantineDryRunResult {
        schema_version: QUARANTINE_RESULT_SCHEMA_VERSION.to_string(),
        source_session_id: plan.source_session_id.clone(),
        mode: "dry-run".to_string(),
        dry_run: true,
        generated_at: Utc::now().to_rfc3339_opts(chrono::SecondsFormat::Millis, true),
        actions: plan
            .plans
            .iter()
            .map(|plan| QuarantineAction {
                plan_id: plan.id.clone(),
                mode: "dry-run".to_string(),
                status: "planned".to_string(),
                asset_ids: plan.asset_ids.clone(),
                error: None,
            })
            .collect(),
    }
}

fn build_review_artifacts(
    session: &MediaCleanSession,
) -> (Vec<LlmReview>, Vec<CleanupPlan>, Vec<QuarantineAction>) {
    let mut reviews = Vec::new();
    let mut plans = Vec::new();
    let mut actions = Vec::new();

    for cluster in &session.clusters {
        push_plan_review(
            &mut reviews,
            &mut plans,
            &mut actions,
            &cluster.id,
            &cluster.category,
            "review",
            "review",
            cluster.asset_ids.clone(),
            true,
        );
    }

    (reviews, plans, actions)
}

fn push_plan_review(
    reviews: &mut Vec<LlmReview>,
    plans: &mut Vec<CleanupPlan>,
    actions: &mut Vec<QuarantineAction>,
    cluster_id: &str,
    category: &str,
    risk: &str,
    action: &str,
    asset_ids: Vec<String>,
    requires_confirmation: bool,
) {
    reviews.push(LlmReview {
        cluster_id: cluster_id.to_string(),
        provider: "fixture".to_string(),
        model: "mc-rust-local-heuristic".to_string(),
        prompt_version: "local-review/v1".to_string(),
        category: category.to_string(),
        confidence: if risk == "safe" { "high" } else { "medium" }.to_string(),
        cleanup_reason: format!("{category} candidate generated by local Rust CLI heuristics"),
        keep_reason: None,
        risk: risk.to_string(),
        suggested_action: action.to_string(),
    });
    let plan_id = format!("plan-{cluster_id}");
    plans.push(CleanupPlan {
        id: plan_id.clone(),
        cluster_id: cluster_id.to_string(),
        action: action.to_string(),
        asset_ids: asset_ids.clone(),
        requires_confirmation,
    });
    actions.push(QuarantineAction {
        plan_id,
        mode: "dry-run".to_string(),
        status: "planned".to_string(),
        asset_ids,
        error: None,
    });
}
