export {
  FoldableLayout,
  HingeSafeArea,
  calculateSplitLayout,
  getEffectiveLayoutStyle,
  useFoldableGridColumns,
  useFoldableLayout,
  type FoldableLayoutConfig,
  type FoldableLayoutProps,
  type GridColumnOptions,
  type HingeMode,
  type HingeSafeAreaProps,
  type UseFoldableLayoutOptions,
  type UseFoldableLayoutResult,
} from '../primitives';
